
name: tf

on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: rdp
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: New-NetFirewallRule -DisplayName "RDP (TCP)" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 3389 -RemoteAddress $RemoteAddress -Profile Any -Enabled True | Out-Null
    - run: New-NetFirewallRule -DisplayName "RDP (UDP)" -Direction Inbound -Action Allow -Protocol UDP -LocalPort 3389 -RemoteAddress $RemoteAddress -Profile Any -Enabled True | Out-Null
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "FBYt_HuB_2024" -Force)
    - name: GetIp
      run: Get-NetIPAddress
    - name: install zrok
      run: Invoke-WebRequest https://github.com/openziti/zrok/releases/download/v0.4.49/zrok_0.4.49_windows_amd64.tar.gz -OutFile $env:temp\zrok.tar.gz
    - name: extract zip
      run: |
            New-Item -Path "$env:TEMP\zrok" -ItemType Directory -ErrorAction Stop
            tar -xf $env:temp\zrok.tar.gz -C "$env:TEMP\zrok"
            $source = Join-Path -Path $env:TEMP -ChildPath "zrok\zrok.exe"
            $destination = Join-Path -Path $env:USERPROFILE -ChildPath "bin\zrok.exe"
            New-Item -Path $destination -ItemType Directory -ErrorAction SilentlyContinue
            Copy-Item -Path $source -Destination $destination
            $env:path += ";"+$destination
            zrok version
            zrok enable 8lvqFsyogiCL
            zrok share private --backend-mode tcpTunnel localhost:3389
